### ISSUE TITLE
ⲧϩⲓⲉⲣⲟⲥⲟⲗⲩⲙⲁ

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/tokenizers#3]
Tokenizer not tokenizing ⲧϩⲓⲉⲣⲟⲥⲟⲗⲩⲙⲁ as ⲧ|ϩⲓⲉⲣⲟⲥⲟⲗⲩⲙⲁ .  See nt.sahidica corpus here:  https://corpling.uis.georgetown.edu/annis/scriptorium#_q=bm9ybV9ncm91cD0v4rKnz6nispPisonisqMuKi8&_c=c2FoaWRpY2EubWFyayxzaGVub3V0ZS5hYnJhaGFtLm91ci5mYXRoZXIsYXBvcGh0aGVnbWF0YS5wYXRydW0sc2FoaWRpY2EuMWNvcmludGhpYW5zLHNhaGlkaWNhLm50LGJlc2EubGV0dGVycyxzaGVub3V0ZS5mb3gsc2hlbm91dGUuYTIy&cl=5&cr=5&s=0&l=10&_seg=b3JpZw
Fix, pending confirmation in email thread from AZ.

**Comment by amir-zeldes** [comment]
This is to do with hierosoluma being tagged as NPROP. We had a version of the tokenizer that allowed NPROP to take articles, but that added substantial errors. We could hardwire this word to be handled correctly, but I'd rather deal with individual errors like this periodically from a cumulative list, rather than re-release for individual words.

**Comment by ctschroeder** [comment]
Understood re NPROP and nlp issues.  Jerusalem is like Satan.  (That would be a great article title, by the way.) 
I think my question is about tokenization:  would it make more sense to train our tagger and tokenizer to recognize Jerusalem and Satan as ART+N rather than as one unit (which would result in a V tag for the unit and then might give other strange tags to following words because the tagger is expecting certain things to follow a verb.)

**Comment by amir-zeldes** [comment]
The tokenizer and tagger use the same lexicon, so to tokenize it right we would have to:

 

-        Hardwire it (might be best)

-        Create a new POS tag (proper but article-compatible)

-        Extend the tagger to do a second pass on unrecognized items that might be definite names (programming effort, but more important potentially leads to errors for things that really shouldn’t be segmented)

-        Or use a different tag in the tokenizer and tagger lexica (not advisable, increases maintenance effort)

 

If it’s only in the lexicon as NPROP, the tagger will always get it right. The question is more about the tokenizer, and if the list of items like this are relatively small, a list based solution might be best. Training on previous segmentations, which is on the agenda, may solve this out of the box though, so I wouldn’t worry about this too much.

**Comment by ctschroeder** [comment]
Thanks.  I defer to you on the best method.  I assumed that if it were tokenized correctly that the tagger would recognize it as an art+n combo.  

Let's keep this issue open, so that when you do your planned work on the tokenizer later this spring, we can revisit the necessity of fixing this and how? I personally don't think this needs to be addressed before then.  This issue can stay open as a reminder.
For reference, here is a search in machine-processed sahidica.nt showing all the non-tokenized jerusalems.  https://corpling.uis.georgetown.edu/annis/scriptorium#_q=bm9ybT0v4rKnz6nispPisonisqMuKi8&_c=c2FoaWRpY2EubnQ&cl=5&cr=5&s=0&l=10&_seg=bm9ybV9ncm91cA

**Comment by amir-zeldes** [comment]
Yeah, I see the cases in Sahidica. The past segmentations feature is honestly the best way to take care of this, since there are few exceptions like this. The tagger will be correct as long as there’s only one tag for that word in the lexicon, which will be NPROP.

**Comment by ctschroeder** [comment]
tokenizer updated; closed
