### ISSUE TITLE
The tokenizer should support morph segmentation for mnt- and other affixes

### ISSUE THREAD

**Issue by bkrawiec** [CopticScriptorium/tokenizers#4]
@amir-zeldes Is the tokenizer separating morphs MNT, REF, AT? If not, can that be added?

**Comment by ctschroeder** [comment]
not urgent.  For consideration *after* the TEI exporter is done IMO

**Comment by amir-zeldes** [comment]
No, not yet. We can keep this issue open as a feature request.

**Comment by amir-zeldes** [comment]
Implemented in V4.X
