### ISSUE TITLE
overdots in text files impede tokenizer function

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/tokenizers#7]
Overdots in text files impede the tokenizer function.  I tried editing lines 191 and 265 of tokenize_coptic.pl (where the other diacritics are) to ensure that the dots are included, but this attempt didn't work.  The tokenizer still did not tokenize bound groups containing overdots.  I am guessing this is an easy fix, but I'm not sure what else to do.

**Comment by ctschroeder** [comment]
Hmmm, I actually think I did partially fix it with my addition of the overdot in line 265.  Never mind.

**Comment by amir-zeldes** [comment]
OK, let me know if I should do anything about this.
